/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DBMSDemo;
import bo.CardCollection;
import bo.CardMarket;
import bo.CardSet;
import bo.UserProfile;
import dao.CardMarketHandler;
import dao.CollectionHandler;
import dao.UserHandler;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author nhinguyen
 */
public class FrmAddCardtoCollection extends javax.swing.JInternalFrame {
    private void populateCollections(){
        List<UserProfile> users = new UserHandler().getUser();
        List<CardMarket> cards = new CardMarketHandler().getCard();
        ComboBoxModel cbxModel = new DefaultComboBoxModel(users.toArray());
        ComboBoxModel cbxModel2 = new DefaultComboBoxModel(cards.toArray());
        cbxUserId.setModel(cbxModel);
        cbxCardId.setModel(cbxModel2);
    }
    /**
     * Creates new form FrmAddCardtoCollection
     */
    public FrmAddCardtoCollection() {
        initComponents();
        populateCollections();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCollectionId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAddtoCollection = new javax.swing.JButton();
        cbxCardId = new javax.swing.JComboBox<>();
        cbxUserId = new javax.swing.JComboBox<>();

        jLabel1.setText("CollectionID");

        jLabel2.setText("CardID");

        jLabel3.setText("UserID");

        jLabel4.setText("Quantity");

        btnAddtoCollection.setText("Add");
        btnAddtoCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoCollectionActionPerformed(evt);
            }
        });

        cbxCardId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxUserId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddtoCollection)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQuantity)
                            .addComponent(txtCollectionId)
                            .addComponent(cbxCardId, 0, 281, Short.MAX_VALUE)
                            .addComponent(cbxUserId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCollectionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxCardId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btnAddtoCollection)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddtoCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoCollectionActionPerformed
        int CollectionID = Integer.parseInt(txtCollectionId.getText());
        int quantity = Integer.parseInt(txtQuantity.getText());
         UserProfile UP = (UserProfile)cbxUserId.getSelectedItem();
         int UserId = UP.getUserId();
         CardMarket CM = (CardMarket)cbxCardId.getSelectedItem();
         int CardId = CM.getCardId();
         //int UserId = GlobalData.user.getUserId();
         int ret = new CollectionHandler().AddCardtoCollection(CollectionID, CardId, UserId, quantity);
         if(ret == - 1){
             JOptionPane.showMessageDialog(this, "Failed to add card");
         }else{
             //Clear the form
             txtCollectionId.setText(null);
             txtQuantity.setText(null);
             cbxUserId.setSelectedItem(0);
             cbxCardId.setSelectedItem(0);
             JOptionPane.showMessageDialog(this, "Card Added");
         }
    }//GEN-LAST:event_btnAddtoCollectionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoCollection;
    private javax.swing.JComboBox<String> cbxCardId;
    private javax.swing.JComboBox<String> cbxUserId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCollectionId;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
