/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBMSDemo;

import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import util.GlobalData;

/**
 *
 * @author nhinguyen
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    FrmLogin frmLogin  = new FrmLogin();
    FrmAddCardtoMarket frmAddUser = new FrmAddCardtoMarket();
    FrmViewCardMarket frmViewUser = new FrmViewCardMarket();
    FrmAddCardtoCollection frmAddCol = new FrmAddCardtoCollection();
    FrmViewCollections frmViewCollections = new FrmViewCollections();
    FrmAddtoWishlist frmAddtoWishlist = new FrmAddtoWishlist();
    FrmViewWishList frmViewWishList = new FrmViewWishList();
    FrmAddCardtoUserDeck frmAddUserDeck = new FrmAddCardtoUserDeck();
    Map<String, JInternalFrame> forms = new HashMap<>();
    Map<String, Boolean> group1Authorization = new HashMap<>();
    
    public FrmMain() {
        initComponents();
        forms.put("frmLogin", frmLogin);
        forms.put("frmAddUser", frmAddUser);
        forms.put("frmViewUser", frmViewUser);
        forms.put("frmAddCol", frmAddCol);
        forms.put("frmViewCollections", frmViewCollections);
        forms.put("frmAddtoWishlist",frmAddtoWishlist);
        forms.put("frmViewWishList", frmViewWishList);
        forms.put("frmAddUserDeck",frmAddUserDeck);
        group1Authorization.put("frmViewUser", Boolean.TRUE);
        group1Authorization.put("frmViewCollections", Boolean.FALSE);
        
        //add these to JDesktopPane
        forms.values().forEach((frm) -> {
            jdpContainer.add(frm);
            
        
    });
    }
    private void showForm(String frmName){
        showForm(frmName,true);
    }
    private void showForm(String frmName, boolean checkLogin){
        if(checkLogin && GlobalData.user == null){
            showForm("frmLogin", false);
        }else{
            try {
                if(forms.get(frmName).isClosed()){
                    try {
                        forms.put(frmName, forms.get(frmName).getClass().newInstance());
                        jdpContainer.add(forms.get(frmName));
                        
                    } catch (InstantiationException | IllegalAccessException ex) {
                        Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                forms.get(frmName).setVisible(true);
                forms.get(frmName).setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpContainer = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniLogin = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mniAdd = new javax.swing.JMenu();
        mniAddUser = new javax.swing.JMenuItem();
        mniUpdateUser = new javax.swing.JMenuItem();
        mniDeleteUser = new javax.swing.JMenuItem();
        mniViewUser = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mniAddCol = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniADD = new javax.swing.JMenuItem();
        mniUPDATE = new javax.swing.JMenuItem();
        mniDELETE = new javax.swing.JMenuItem();
        mniVIEW = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpContainer.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jdpContainerLayout = new javax.swing.GroupLayout(jdpContainer);
        jdpContainer.setLayout(jdpContainerLayout);
        jdpContainerLayout.setHorizontalGroup(
            jdpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdpContainerLayout.setVerticalGroup(
            jdpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        getContentPane().add(jdpContainer, java.awt.BorderLayout.CENTER);

        mnuFile.setText("File");

        mniLogin.setText("Login...");
        mniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoginActionPerformed(evt);
            }
        });
        mnuFile.add(mniLogin);

        mniLogout.setText("Logout...");
        mnuFile.add(mniLogout);

        mniExit.setText("Exit");
        mnuFile.add(mniExit);

        jMenuBar1.add(mnuFile);

        mnuManage.setText("Manage");

        mniAdd.setText("Cards in Market");

        mniAddUser.setText("Add");
        mniAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddUserActionPerformed(evt);
            }
        });
        mniAdd.add(mniAddUser);

        mniUpdateUser.setText("Update");
        mniUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUpdateUserActionPerformed(evt);
            }
        });
        mniAdd.add(mniUpdateUser);

        mniDeleteUser.setText("Delete");
        mniDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeleteUserActionPerformed(evt);
            }
        });
        mniAdd.add(mniDeleteUser);

        mniViewUser.setText("View");
        mniViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewUserActionPerformed(evt);
            }
        });
        mniAdd.add(mniViewUser);

        mnuManage.add(mniAdd);

        jMenu1.setText("Card Collection");

        mniAddCol.setText("Add Card to Collection");
        mniAddCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddColActionPerformed(evt);
            }
        });
        jMenu1.add(mniAddCol);

        jMenuItem2.setText("Update Collection");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Delete Card from Collection");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("View Collection");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        mnuManage.add(jMenu1);

        jMenu3.setText("Wish List");

        mniADD.setText("Add Card to Wish List");
        mniADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniADDActionPerformed(evt);
            }
        });
        jMenu3.add(mniADD);

        mniUPDATE.setText("Update Wish List");
        mniUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUPDATEActionPerformed(evt);
            }
        });
        jMenu3.add(mniUPDATE);

        mniDELETE.setText("Delete Card from Wish List");
        mniDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDELETEActionPerformed(evt);
            }
        });
        jMenu3.add(mniDELETE);

        mniVIEW.setText("View Wish List");
        mniVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVIEWActionPerformed(evt);
            }
        });
        jMenu3.add(mniVIEW);

        mnuManage.add(jMenu3);

        jMenu2.setText("User Deck");

        jMenuItem1.setText("Add");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem5.setText("View");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Delete");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Update");
        jMenu2.add(jMenuItem7);

        mnuManage.add(jMenu2);

        jMenuBar1.add(mnuManage);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
        showForm("frmLogin",false);
    }//GEN-LAST:event_mniLoginActionPerformed

    private void mniDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeleteUserActionPerformed
        showForm("frmViewUser");
    }//GEN-LAST:event_mniDeleteUserActionPerformed

    private void mniAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddUserActionPerformed
       
        showForm("frmAddUser");
    }//GEN-LAST:event_mniAddUserActionPerformed

    private void mniViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewUserActionPerformed
        
        showForm("frmViewUser");
    }//GEN-LAST:event_mniViewUserActionPerformed

    private void mniAddColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddColActionPerformed
        
        showForm("frmAddCol");
    }//GEN-LAST:event_mniAddColActionPerformed

    private void mniUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUpdateUserActionPerformed
        showForm("frmViewUser");
    }//GEN-LAST:event_mniUpdateUserActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        showForm("frmViewCollections");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        showForm("frmViewCollections");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        showForm("frmViewCollections");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mniVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVIEWActionPerformed
        showForm("frmViewWishList");
    }//GEN-LAST:event_mniVIEWActionPerformed

    private void mniDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDELETEActionPerformed
        showForm("frmViewWishList");
    }//GEN-LAST:event_mniDELETEActionPerformed

    private void mniADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniADDActionPerformed
        showForm("frmAddtoWishlist");
    }//GEN-LAST:event_mniADDActionPerformed

    private void mniUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUPDATEActionPerformed
        showForm("frmViewWishList");
    }//GEN-LAST:event_mniUPDATEActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        showForm("frmAddUserDeck");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmMain frmMain = new FrmMain();
                frmMain.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                frmMain.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JDesktopPane jdpContainer;
    private javax.swing.JMenuItem mniADD;
    private javax.swing.JMenu mniAdd;
    private javax.swing.JMenuItem mniAddCol;
    private javax.swing.JMenuItem mniAddUser;
    private javax.swing.JMenuItem mniDELETE;
    private javax.swing.JMenuItem mniDeleteUser;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniUPDATE;
    private javax.swing.JMenuItem mniUpdateUser;
    private javax.swing.JMenuItem mniVIEW;
    private javax.swing.JMenuItem mniViewUser;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuManage;
    // End of variables declaration//GEN-END:variables
}
