/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DBMSDemo;

import static DBMSDemo.FrmUpdateCardMarket.RET_CANCEL;
import static DBMSDemo.FrmUpdateCardMarket.RET_OK;
import bo.CardCollection;
import bo.CardMarket;
import bo.CardSet;
import bo.UserProfile;
import dao.CardMarketHandler;
import dao.CollectionHandler;
import dao.SetHandler;
import dao.UserHandler;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nhinguyen
 */



public class FrmUpdateCollections extends javax.swing.JDialog {
public static final int RET_OK = 1;
public static final int RET_CANCEL = 0;
    /**
     * Creates new form UpdateCollections
     */
    List<UserProfile> users;
    List<CardMarket> cards;
    private void populateCollections(){
        users = new UserHandler().getUser();
        cards = new CardMarketHandler().getCard();
        ComboBoxModel cbxModel = new DefaultComboBoxModel(users.toArray());
        ComboBoxModel cbxModel2 = new DefaultComboBoxModel(cards.toArray());
        cbxUserId.setModel(cbxModel);
        cbxCardId.setModel(cbxModel2);
    }
    private CardCollection card;
    public void setCard(CardCollection card){
        this.card = card;
        txtCollectionId.setText(String.valueOf(card.getCollectionId()));
        txtQuantity.setText(String.valueOf(card.getQuantity()));
        cards.forEach(se -> {
            if (se.getCardId() == card.getCardId()) {
            cbxCardId.setSelectedItem(se);
            }});
        users.forEach(se -> {
            if (se.getUserId() == card.getUserId()) {
            cbxUserId.setSelectedItem(se);
            }
        });
    }
  
     public FrmUpdateCollections(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populateCollections();
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCollectionId = new javax.swing.JTextField();
        cbxCardId = new javax.swing.JComboBox<>();
        cbxUserId = new javax.swing.JComboBox<>();

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("CollectionID");

        jLabel6.setText("UserID");

        jLabel2.setText("CardID");

        jLabel3.setText("Quantity");

        txtCollectionId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCollectionIdActionPerformed(evt);
            }
        });

        cbxCardId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCardId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCardIdActionPerformed(evt);
            }
        });

        cbxUserId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUserIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(txtCollectionId))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(cbxCardId, 0, 305, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxUserId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtQuantity))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtCollectionId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxCardId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(27, 27, 27))
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        int CollectionId = Integer.parseInt(txtCollectionId.getText());
        int Quantity = Integer.parseInt(txtQuantity.getText());
        String CardName = null;
        UserProfile UP = (UserProfile)cbxUserId.getSelectedItem();
         int UserId = UP.getUserId();
        CardMarket CM = (CardMarket)cbxCardId.getSelectedItem();
         int CardId = CM.getCardId();
        int ret = new CollectionHandler().updateCard(CollectionId, CardId,  UserId, Quantity, CardName);
        if (ret!=-1){
            doClose(RET_OK);
        }else{
            JOptionPane.showMessageDialog(this, "Failed to update Card");
        }

    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void txtCollectionIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCollectionIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCollectionIdActionPerformed

    private void cbxCardIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCardIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCardIdActionPerformed

    private void cbxUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxUserIdActionPerformed
    private void closeDialog(java.awt.event.WindowEvent evt) {                             
        doClose(RET_CANCEL);
    }  
private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
public int getReturnStatus() {
        return returnStatus;
    }
private int returnStatus = RET_CANCEL;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cbxCardId;
    private javax.swing.JComboBox<String> cbxUserId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField txtCollectionId;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
